### ISSUE TITLE
maxBlockPlaceDistance与maxBlockPlaceDistanceReferToEntity规则不适用于服务器

### ISSUE THREAD

**Issue by 1024-byteeeee** [cdqtzrc/Carpet-Org-Addition#13]
服务器开启规则后，客户端进入服务器依然无法获得修改后的放置距离。

**Comment by cdqtzrc** [comment]
Carpet本体的锅

**Comment by cdqtzrc** [comment]
> 我的问题，maxBlockPlaceDistance规则依然需要客户端修改了放置距离。

是的，虽然1.20.5引入了新的属性值，但我依然想将客户端的放置距离的调整交给客户端实现。
