### ISSUE TITLE
simpleUpdateSkipper不起作用于1.20.2

### ISSUE THREAD

**Issue by nkkejj** [cdqtzrc/Carpet-Org-Addition#14]
输入指令/carpet simpleUpdateSkippe True后使用跳略器依旧不起作用，不断跳线

**Comment by cdqtzrc** [comment]
音符盒跳略器是有方向性的，其它朝向也跳线吗

**Comment by cdqtzrc** [comment]
> 没事了，拿到唱片机了

倒不是唱片机的问题，不管是不是你放置的朝向有问题，都请告诉我，如果这确实是你放置的朝向有问题，那么这个issue将被关闭，否则当做一个bug处理

**Comment by nkkejj** [comment]
更改后并未有问题，感谢您的帮助
