### ISSUE TITLE
[bug] 禁止和平模式下持久生物被清除(disableMobPeacefulDespawn)

### ISSUE THREAD

**Issue by vocaloidkiss** [cdqtzrc/Carpet-Org-Addition#15]
导致所有具有此标签的生物[命名，手持物品，骑乘，等其他不消失生物]在转变时。如蠹虫钻入，溺尸转化，村民转女巫，村民转僵尸村民，猪灵疣猪兽转僵尸猪灵疣猪兽，哞菇转颜色等
不会销毁原生物，反而不断复制，生成大量转化后生物，在服务器曾有天然拾取掉落物的泡水僵尸转化了6400只溺尸卡服，

**Comment by cdqtzrc** [comment]
这个bug的原因是MC里生物转化实际上是创建一个新的出来，然后把原来的生物删掉，开了这个功能之后，原有的生物就删不掉了

**Comment by cdqtzrc** [comment]
下个版本会修的
