### ISSUE TITLE
关于使用瞬时传送带进行虚空交易的问题

### ISSUE THREAD

**Issue by ByakuyX** [cdqtzrc/Carpet-Org-Addition#16]
因为瞬时传送带虚空交易的情形下，村民会在弱加载和加载边界之间移动，完成交易的时机是村民在加载边界时；
mod的虚空交易功能需要等到村民被卸载才能进行交易，这导致假人不能依靠此mod进行瞬时传送带虚空交易。
希望能改善这个问题qwq

**Comment by ziyujiang1** [comment]
感觉可以对现有的功能进行新的注释，比如在非虚空交易模式下，假人在打开村民gui后需等待>10gt(大概，我猜的)

后再进行交易？

**Comment by cdqtzrc** [comment]
我调整了虚空交易的时机，现在它可以使用瞬时传送带进行虚空交易

**Comment by ziyujiang1** [comment]
cool

**Comment by cdqtzrc** [comment]
https://github.com/cdqtzrc/Carpet-Org-Addition/releases/tag/v1.31.0
