### ISSUE TITLE
1.21没有protectionEnchantmentCompatible

### ISSUE THREAD

**Issue by Spturate** [cdqtzrc/Carpet-Org-Addition#17]
![image](https://github.com/cdqtzrc/Carpet-Org-Addition/assets/30800649/ea7bc9b2-97d9-4410-b69c-fc4a12048dc8)
carpet 和 carpet org是最新的版本

**Comment by cdqtzrc** [comment]
原版1.21中可以用数据包实现这些功能，所以我把这几条规则移除了
