### ISSUE TITLE
希望能添加回一个特性

### ISSUE THREAD

**Issue by torresmamon** [cdqtzrc/Carpet-Org-Addition#18]
海豚复制特性在1.16.5之后的版本被修复，希望作者能重新引入

**Comment by cdqtzrc** [comment]
如果只是为了复制物品，可以试试另外两条规则：`制作物品分身`和`CCE更新抑制器`，如果是制作物品分身，你只需要将要复制的物品拿在主手，副手空着，然后执行/itemshadowing命令，接着退出重进就可以了；对于CCE更新抑制器，如果你担心游戏崩溃，可以试试Carpet TIS Addition的更新抑制放崩溃功能

**Comment by torresmamon** [comment]
我是因为打算升级版本，舍不得海豚复制特性。我个人认为制作物品分身和CCE更新抑制器有点过于破坏平衡，跟骑羊驼复制一样，所有希望作者能加回这个特性。如果您本人不喜欢特性或者觉得加回这个特性过于繁琐，我将不在打扰您，多谢。
