### ISSUE TITLE
击退棒不可用，开启击退棒后木棍仍然不可附魔击退

### ISSUE THREAD

**Issue by oneIdler** [cdqtzrc/Carpet-Org-Addition#19]
![QQ_1720922683849](https://github.com/user-attachments/assets/f46e3823-35fb-4bcf-a2b7-b58276e574d5)
![QQ_1720922708286](https://github.com/user-attachments/assets/beb63b76-d13e-443e-89e3-73b684673b8c)
![QQ_1720922715709](https://github.com/user-attachments/assets/3afddc25-7d2c-4a9c-96fd-c089736683a7)

**Comment by oneIdler** [comment]
1.21

**Comment by cdqtzrc** [comment]
可以复现，正在尝试修复

**Comment by cdqtzrc** [comment]
下个版本修复

**Comment by cdqtzrc** [comment]
新版本发布了，并且击退棒功能已经修复。但是，1.21中mojang对附魔进行了大改，不好直接判断当前附魔是否为击退附魔，所以，现在模组以附魔的功能来判断是否为击退附魔，这导致了任何有击退效果的附魔都可以被附魔到木棍上，例如冲击（尽管它在木棍上不会生效）。
