### ISSUE TITLE
A problem about fakeplayer relogin

### ISSUE THREAD

**Issue by Fashionrock** [cdqtzrc/Carpet-Org-Addition#21]
A player made the fakeplayer relogin as often as 2gt on my server, after a few minutes the server mspt increased to a really high value， killing the fakeplayer still didn't fix the problem unless the server was restarted

**Comment by wendavid552** [comment]
This issue relates to memory leak of fake player spawning in `fabric-carpet`, and could be considered as a compatability issue between `fabric-carpet` and `fabric-api`. Refer to

https://github.com/FabricMC/fabric/issues/3974

and

https://github.com/gnembon/fabric-carpet/issues/1957

Here's your possiblt solution:
- Remove `fabric-api` or `fabric-carpet`
- Wait until `fabric-api` or `fabric-carpet` to upgrade
- Wait for us to make a temporarily fix for it

I am doing development about fixing this bug temporarily from Carpet-Org-Addition.


该问题与`fabric-carpet`生成假人时的内存泄露有关，是`fabric-carpet`与`fabric-api`的兼容性问题。参考

https://github.com/FabricMC/fabric/issues/3974

和

https://github.com/gnembon/fabric-carpet/issues/1957

以下是可能的解决方案：
- 删除`fabric-api`或`fabric-carpet`其中一个
- 等待`fabric-api`以及`fabric-carpet`更新
- 等待我们对此进行一个临时修复

我正在针对此问题进行临时修复的开发。
