### ISSUE TITLE
1.21下，通过simpleUpdateSkipper规则开启的更新跳略器无法复制物品

### ISSUE THREAD

**Issue by ImYiFeng** [cdqtzrc/Carpet-Org-Addition#24]
在1.21版本的Carpet Org Addition下，开启simpleUpdateSkipper规则，建造两个音符盒那样的更新跳略器，可以切门，但无法复制物品。尝试了网上几种基于这个特性的物品复制，都不能使用

**Comment by wendavid552** [comment]
Update skipper是跳略器，你要的物品复制的特性是抑制器的。

**Comment by cdqtzrc** [comment]
跳略器不是抑制器，不能用来物品复制

**Comment by cdqtzrc** [comment]
如果你确实需要复制物品，可以试试另一条规则：`CCEUpdateSuppression`

**Comment by ImYiFeng** [comment]
> 跳略器不是抑制器，不能用来物品复制

网上倒是有用这个跳略器复制物品的方法，我在1.18原版也可以复现，但在开了simpleUpdateSkipper的1.21就不行

**Comment by cdqtzrc** [comment]
> > 跳略器不是抑制器，不能用来物品复制
> 
> 网上倒是有用这个跳略器复制物品的方法，我在1.18原版也可以复现，但在开了simpleUpdateSkipper的1.21就不行

这种结构在1.18以下是抑制器，1.19以上是跳略器

**Comment by ImYiFeng** [comment]
> > > 跳略器不是抑制器，不能用来物品复制
> > 
> > 
> > 网上倒是有用这个跳略器复制物品的方法，我在1.18原版也可以复现，但在开了simpleUpdateSkipper的1.21就不行
> 
> 这种结构在1.18以下是抑制器，1.19以上是跳略器

懂了，谢谢解答

**Comment by cdqtzrc** [comment]
> > 跳略器不是抑制器，不能用来物品复制
> 
> 网上倒是有用这个跳略器复制物品的方法，我在1.18原版也可以复现，但在开了simpleUpdateSkipper的1.21就不行

你可以在原版1.19中试一下，应该也是无法复制物品的
