### ISSUE TITLE
服务端后台有一串未知的错误，不知道是不是org的原因

### ISSUE THREAD

**Issue by LLovelyMrzheng** [cdqtzrc/Carpet-Org-Addition#27]
[Server] [17:25:02] [main/WARN]: Error loading class: net/minecraft/class_757 (java.lang.ClassNotFoundException: net/minecraft/class_757)
[Server] [17:25:02] [main/WARN]: @Mixin target net.minecraft.class_757 was not found carpet_org_addition.mixins.json:rule.playerinteraction.GameRendererMixin from mod carpet-org-addition

**Comment by cdqtzrc** [comment]
它对游戏是否游戏影响

**Comment by LLovelyMrzheng** [comment]
暂未发现对服务端和客户端有任何影响，仅仅是反馈一下这个错误

**Comment by cdqtzrc** [comment]
没有必要关闭这个issue，因为它确实算是一个bug

**Comment by wendavid552** [comment]
> 没有必要关闭这个issue，因为它确实算是一个bug

把Mixin的位置换一下就可以了，应该是得放到client那边？
