### ISSUE TITLE
是否可以添加对声音更新抑制器的支持

### ISSUE THREAD

**Issue by PPGC777** [cdqtzrc/Carpet-Org-Addition#29]
IAE更新抑制器(IAEUpdateSuppression)
就像重命名潜影盒为"更新抑制器"那样, 重命名陷阱箱为"更新抑制器";

**Comment by cdqtzrc** [comment]
更新抑制有一个就够了，不考虑加入第二条抑制器规则

**Comment by PPGC777** [comment]
> 更新抑制有一个就够了，不考虑加入第二条抑制器规则

但是声音抑制器可以做到在一个范围内的声音检测和抑制, 借此可以做到AFK的物品复制;
CCE更新抑制好像只能做到在活板门上放比较器然后在背面展示框复制物品, 并且比较器在复制物品后会掉落, 1.20.1之后的版本甚至不能在open状态的活板门上放置

希望可以再考虑下, 打扰了

**Comment by cdqtzrc** [comment]
你可以使用规则“CCEUpdateSuppression”制作声音抑制器

**Comment by PPGC777** [comment]
> 你可以使用规则“CCEUpdateSuppression”制作声音抑制器

1.21后续版本修复了声音更新抑制, 后续版本是否会考虑增加开启的规则或者合并到`CCEUpdateSuppression`当中
以及在`playerAction`中有没有实现让假人对着展示框按指定周期执行`先右键 再左键`的操作, 用以实现假人AFK挂机的操作 (目前好像carpet和相关mod暂时没有防止`IllegalArgumentException`崩溃的功能 无法测试; 只在purpur的服务端尝试过使用两个假人 一个假人执行`use interval 1` 一个假人执行`attack interval 1`来做到2gt刷物品)

**Comment by cdqtzrc** [comment]
目前不会考虑加入第二个抑制器，也不考虑加入让假人定时左键右键的功能。另外，几十分钟前carpet tis addition发布了新版本，现在更新抑制放崩溃可以防止声音抑制器崩服

**Comment by PPGC777** [comment]
> 目前不会考虑加入第二个抑制器，也不考虑加入让假人定时左键右键的功能。另外，几十分钟前carpet tis addition发布了新版本，现在更新抑制防崩溃可以防止声音抑制器崩服

已更新carpet TIS addition测试, 虽然防止崩服了, 但是在抑制器范围内让假人对着展示框执行`use once`IAE异常并会阻止后续的假人动作判断, 假人会认为`use`指令未执行, 于是反复执行`use once`指令; 假人挂机破灭...
还有就是 假人执行`use once`时, 真人进行左键操作虽然可以复制展示框物品 但是此时无法拾取物品; 漏斗矿车可以吸走复制的物品 但是漏斗矿车下的漏斗不能吸走漏斗矿车内的物品

无解了...
