### ISSUE TITLE
村民交易BUG

### ISSUE THREAD

**Issue by No-Name-NoNa** [cdqtzrc/Carpet-Org-Addition#31]
1.21
村民被假人打折一次后，
进行船交时出现:   1线->1绿宝石
不打折以及用假人正常交易的时候 , 是正常的

**Comment by cdqtzrc** [comment]
经过测试，这是原版游戏中的bug，你可以在原版游戏中使用真玩家再测试一遍，如果依然存在问题，请到漏洞追踪器向官方提交：请到漏洞追踪器向官方提交：https://bugs.mojang.com/projects/MC/issues

**Comment by cdqtzrc** [comment]
但我担心的是，如果提交了，会不会连着虚空交易一起修复

**Comment by cdqtzrc** [comment]
别提交！留着！

**Comment by cdqtzrc** [comment]
藏起来！别让Mojang知道！
