### ISSUE TITLE
有关于"更好的不死图腾 BetterTotemOfUndying"的规则特性/bug

### ISSUE THREAD

**Issue by ChiLinCN** [cdqtzrc/Carpet-Org-Addition#33]
该规则选择shulker_box后 即使玩家背包里或背包里的潜影盒里没有不死图腾 
在玩家死亡时依然能触发不死图腾(而且似乎该规则下潜影盒内有不死图腾触发后也不消耗...?)

**Comment by cdqtzrc** [comment]
告诉我你的游戏和模组版本

**Comment by cdqtzrc** [comment]
最新版已经修复了这个问题，有在最新版测试过吗

**Comment by ChiLinCN** [comment]
mc1.21-v1.33.1-2408091358
实测在更新完后已无相关问题=-=
