### ISSUE TITLE
添加一个功能

### ISSUE THREAD

**Issue by Young912** [cdqtzrc/Carpet-Org-Addition#7]
大佬您好，能不能麻烦添加一个功能禁止僵尸捡怪物掉落物之类的。怪物在矿洞会莫名其妙嗝屁，一些僵尸就去捡。。比如箭、火药、腐肉、骨头、鸡蛋等一系列掉落物。这些怪物没法消失导致怪越堆越多会造成卡顿。非常感谢！
![1](https://github.com/cdqtzrc/Carpet-Org-Addition/assets/43774123/6d0f4a4d-4ca3-4858-8f60-e52ec9b488ec)

**Comment by cdqtzrc** [comment]
好的

**Comment by Young912** [comment]
大佬有没有什么办法设置就是，设置一个物品列表，让僵尸不捡这个物品列表里面的特定掉落物，其他的可以照捡的

**Comment by cdqtzrc** [comment]
暂时不好实现

**Comment by cdqtzrc** [comment]
倒是可以用解析字符串的方式，但是我担心会有性能问题

**Comment by Young912** [comment]
好的，谢谢您，模组很棒

**Comment by cdqtzrc** [comment]
新版本发布了，去看看吧
