### ISSUE TITLE
易碎黑曜石在1.20.4服务器中 无法使用

### ISSUE THREAD

**Issue by KleinQwQ** [cdqtzrc/Carpet-Org-Addition#8]
在单人存档中打开易碎黑曜石功能可以使用
但是在服务器中打开无法达到实现易碎

**Comment by cdqtzrc** [comment]
试试关闭易碎深板岩后能不能易碎

**Comment by cdqtzrc** [comment]
https://github.com/cdqtzrc/Carpet-Org-Addition/releases/tag/v1.25.1
